#include "Definitions.h"

const char* HERO_TAG_NAME = "hero";
const char* EVENT_CONTROLLER_LEFT = "LEFT CONTROLLER EVENT";
const char* EVENT_CONTROLLER_RIGHT = "RIGHT CONTROLLER EVENT";
const char* EVENT_FIRE_EVENT = "DIRECTION EVENT";
const char* EVENT_HEALTH_PERCENT = "HEALTH PERCENT EVENT";
const char* EVENT_HERO_DIED = "HERO DIED EVENT";
const float HERO_HEALTH = 500;